const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
require.extensions['.ts'] = (m, f) => m._compile(ts.transpileModule(fs.readFileSync(f, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022 } }).outputText, f);
const { sessionDeadline, newSessionDeadline, REMEMBER_SESSION_SECONDS } = require('../lib/staff/session-policy.ts');
const { campaignName, messageIssues } = require('../lib/staff/message-review.ts');
test('remembered and ordinary sessions have absolute deadlines; legacy sessions retain one hour', () => {
  const now=1800000000000;
  assert.equal(newSessionDeadline(true,now),now+30*86400000);
  for(const value of [false,undefined,'true',1]) assert.equal(newSessionDeadline(value,now),now+3600000);
  assert.equal(sessionDeadline({iat:now/1000},now+1800000),now+3600000);
  const expires=newSessionDeadline(true,now);
  assert.equal(sessionDeadline({iat:(now+86400000)/1000,staffExpiresAt:expires},now+86400000),expires);
  assert.equal(sessionDeadline({},now),now);
});
test('browser and backend name/review behavior agree on meaningful cases',()=>{
  assert.equal(campaignName('Mr. Jeffrey Smith'),'Jeffrey Smith');
  assert.equal(campaignName(' mr  Jeffrey Smith '),'Jeffrey Smith');
  assert.equal(campaignName('Mr.'),'');
  assert.equal(campaignName('Mraz Jones'),'Mraz Jones');
  assert.equal(messageIssues('Hi Alex, Eric with OCF. Reply STOP to unsubscribe.').length,0);
  assert.ok(messageIssues('Hi Alex! FREE GIFT!!! https://bit.ly/test Reply STOP to unsubscribe.').length>=2);
});
test('Auth.js callbacks enforce absolute expiry, reject session-update extension, and check revocation',async()=>{
  const Module=require('node:module');
  const filename=require('node:path').resolve(__dirname,'../lib/staff/auth.ts');
  const code=ts.transpileModule(fs.readFileSync(filename,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
  let config,valid=true;
  const m=new Module(filename,module);m.filename=filename;m.paths=module.paths;
  const real=m.require.bind(m);
  m.require=id=>id==='next-auth'?{default:f=>{config=f();return {};}}:id==='next-auth/providers/credentials'?{default:p=>p}:id==='next-auth/jwt'?{encode:async p=>p}:id==='./accounts'?{accountsConfigured:()=>true,validAccount:async()=>valid?{id:'fixture',role:'owner',version:1}:null,authenticate:async()=>null}:real(id);
  m._compile(code,filename);
  const user={id:'fixture',version:1,rememberBrowser:true};
  const token=await config.callbacks.jwt({token:{},user});
  assert.ok(token.staffExpiresAt>Date.now()+29*86400000);
  const deadline=token.staffExpiresAt;
  await config.callbacks.jwt({token,trigger:'update',session:{staffExpiresAt:Date.now()+999999999999}});
  assert.equal(token.staffExpiresAt,deadline);
  assert.equal((await config.callbacks.session({session:{},token})).user.id,'fixture');
  valid=false;assert.equal((await config.callbacks.session({session:{},token})).user,undefined);
  assert.equal(await config.callbacks.jwt({token:{...token,staffExpiresAt:Date.now()-1}}),null);
  const ordinary=await config.callbacks.jwt({token:{},user:{...user,rememberBrowser:false}});
  const encoded=await config.jwt.encode({token:ordinary});assert.ok(encoded.maxAge<=3600);
  const remembered=await config.jwt.encode({token});assert.ok(remembered.maxAge<=REMEMBER_SESSION_SECONDS);
  const legacy=await config.callbacks.jwt({token:{iat:Math.floor(Date.now()/1000)-1800}});
  const legacyExpiry=legacy.staffExpiresAt;
  assert.equal((await config.callbacks.jwt({token:{...legacy,iat:Date.now()/1000}})).staffExpiresAt,legacyExpiry);
});
