'use client';
import { FormEvent, useEffect, useState } from 'react';
type Account = { id: string; name: string; email: string; role: string; enabled: boolean };
export default function AccessManager() {
  const [accounts, setAccounts] = useState<Account[]>([]); const [pending, setPending] = useState<{ email: string; name: string }[]>([]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [link, setLink] = useState('');
  async function refresh() { const r = await fetch('/api/staff/access', { cache: 'no-store' }); const b = await r.json(); if (!r.ok) throw new Error(b.error); setAccounts(b.accounts); setPending(b.pending); }
  useEffect(() => { refresh().catch(e => setError(e.message)); }, []);
  async function update(action: string, input: object) { setBusy(true); setError(''); setLink(''); setMessage(''); try { const r = await fetch('/api/staff/access', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ action, ...input }), cache: 'no-store' }); const b = await r.json(); if (!r.ok) throw new Error(b.error); setMessage(b.message); setLink(b.link || ''); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : 'Update failed.'); } finally { setBusy(false); } }
  async function invite(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const f = new FormData(e.currentTarget); await update('invite', { email: f.get('email'), name: f.get('name') }); }
  return <main className="staff-settings"><a href="/staff">Back to dashboard</a><h1>Access management</h1><p>Only you can invite people or remove access. Each person chooses their own password.</p>{error && <div className="staff-alert" role="alert">{error}</div>}{message && <p role="status">{message}</p>}{link && <section className="staff-panel"><label htmlFor="private-link">Private setup or reset link</label><input id="private-link" readOnly value={link} onFocus={e => e.target.select()} /><p>Share this link privately with the intended person. It works once. No email has been sent.</p><button className="staff-secondary" onClick={async () => { try { await navigator.clipboard.writeText(link); setMessage('Link copied.'); } catch { setMessage('Select and copy the link above.'); } }}>Copy private link</button></section>}
    <section className="staff-panel"><h2>Invite a person</h2><form onSubmit={invite}><label htmlFor="invite-name">Name</label><input id="invite-name" name="name" maxLength={80} required /><label htmlFor="invite-email">Email</label><input id="invite-email" name="email" type="email" maxLength={254} required /><button className="staff-primary" disabled={busy}>Create private invitation</button></form></section>
    <section className="staff-panel"><h2>Approved accounts</h2>{accounts.map(a => <div className="staff-access-row" key={a.id}><div><strong>{a.name}</strong><p>{a.email} · {a.role === 'owner' ? 'Owner' : 'Staff'} · {a.enabled ? 'Enabled' : 'Disabled'}</p></div><div><button className="staff-secondary" disabled={busy || !a.enabled} onClick={() => update('reset', { id: a.id })}>Reset password</button>{a.role !== 'owner' && <button className="staff-secondary" disabled={busy} onClick={() => { if (a.enabled && !window.confirm(`Remove access for ${a.name}? They will be signed out.`)) return; update(a.enabled ? 'disable' : 'enable', { id: a.id }); }}>{a.enabled ? 'Remove access' : 'Enable access'}</button>}</div></div>)}</section>
    {pending.length > 0 && <section className="staff-panel"><h2>Invitations awaiting setup</h2>{pending.map(p => <div className="staff-access-row" key={p.email}><p>{p.name} · {p.email}</p><button className="staff-secondary" disabled={busy} onClick={() => update('cancel', { email: p.email })}>Cancel invitation</button></div>)}<p>Create another invitation for the same email to replace its previous link.</p></section>}
  </main>;
}
