'use client';
import {useState} from 'react';
import {campaignName} from '@/lib/staff/message-review';
const services=['Christmas lighting','Gutter cleaning','Window cleaning','House washing','Driveway / sidewalk cleaning','Roof cleaning','Drainage cleaning'];
type Decision={status:string;scope?:string;services?:string[];recordedAt:string;version:number};
type Row={id:string;name:string;clientId?:string;phone?:string;phoneId?:string;propertyId?:string;decision?:Decision|null;issue?:string};
type Props={request:(body:Record<string,unknown>)=>Promise<any>;disabled:boolean;onRefresh:()=>Promise<void>;onContinue:()=>void};
function label(d?:Decision|null){if(!d||d.status==='unknown')return '';if(d.status==='declined')return 'Do not send';return d.scope==='all'?'Accepted all texts':'Accepted selected services';}
export default function BulkPermissions({request,disabled,onRefresh,onContinue}:Props){
 const [rows,setRows]=useState<Row[]>([]),[selected,setSelected]=useState<string[]>([]),[after,setAfter]=useState<string|null>(null),[more,setMore]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[mode,setMode]=useState('none'),[chosenServices,setChosenServices]=useState<string[]>([]),[note,setNote]=useState(''),[filter,setFilter]=useState('all');
 const locked=disabled||busy,chosen=rows.filter(r=>selected.includes(r.id)&&r.phone),visible=rows.filter(r=>filter==='all'||(filter==='blocked'&&(r.issue||r.decision?.status==='declined'))||(filter==='unverified'&&(!r.decision||r.decision.status==='unknown')));
 async function load(){setBusy(true);setError('');try{const page=await request({operation:'clients',after});const customers=page.records.filter((r:any)=>!r.isArchived&&!r.isLead&&!rows.some(x=>x.id===r.id));let next=[...rows];const seen=new Set(rows.map(r=>r.phone).filter(Boolean));for(const c of customers){setNotice(`Loading saved details: ${campaignName(c.name)}`);let row:Row={id:c.id,name:campaignName(c.name)};try{const details=await request({operation:'permission_customer',id:c.id});if(seen.has(details.phone))row.issue='Shared number already listed. Edit its first matching row.';else{seen.add(details.phone);row={...row,...details};}}catch(e){row.issue=e instanceof Error?e.message:'Could not load this record.';}next=[...next,row];setRows(next);}setAfter(page.pageInfo.endCursor);setMore(page.pageInfo.hasNextPage);setNotice('List loaded. Select customers, choose a permission, then Save selected. Blank cells mean not verified.');}catch(e){setError(e instanceof Error?e.message:'Could not load clients.');}finally{setBusy(false);}}
 async function save(){if(mode==='none'||!chosen.length||(mode==='services'&&!chosenServices.length))return;setBusy(true);setError('');let saved=0,failed=0;for(const row of chosen){setNotice(`Saving ${saved+failed+1} of ${chosen.length}: ${row.name}`);try{const result=await request({operation:'permission_save',clientId:row.clientId,phone:row.phone,phoneId:row.phoneId,propertyId:row.propertyId,status:mode==='declined'?'declined':mode==='unknown'?'unknown':'accepted',scope:mode==='all'?'all':'services',services:mode==='services'?chosenServices:['Christmas lighting'],note,version:row.decision?.version||0});setRows(old=>old.map(r=>r.id===row.id?{...r,decision:result.decision,issue:undefined}:r));saved++;setSelected(old=>old.filter(id=>id!==row.id));}catch(e){failed++;setRows(old=>old.map(r=>r.id===row.id?{...r,issue:e instanceof Error?e.message:'Save not verified. Reload before retrying.'}:r));}}try{await onRefresh();}catch{}setNotice(`${saved} saved. ${failed} need attention. No messages sent.`);setBusy(false);}
 return <section className="staff-panel"><span className="staff-eyebrow">CUSTOMER PERMISSIONS</span><h2>Edit your customer list in one place.</h2><p>Select a group and save your report of what those customers agreed to. No need to open and accept each customer individually.</p><p className="staff-small">Names and numbers come from Jobber. Permissions save directly to this website and are reused during campaign review. Blank means not verified. Recorded STOP requests still block sending.</p>{error&&<p role="alert">{error}</p>}{notice&&<p role="status" aria-live="polite">{notice}</p>}<div className="xmas-actions">{more&&<button className="staff-secondary" disabled={locked} onClick={load}>{rows.length?'Load next 200 customers':'Load up to 200 customers'}</button>}<button className="staff-secondary" disabled={locked||!rows.length} onClick={()=>setSelected(visible.filter(r=>r.phone).map(r=>r.id))}>Select all shown</button><button className="staff-secondary" disabled={locked} onClick={()=>setSelected([])}>Clear selection</button><label>Show<select value={filter} disabled={locked} onChange={e=>setFilter(e.target.value)}><option value="all">All loaded customers</option><option value="blocked">Do not send / needs attention</option><option value="unverified">Not verified</option></select></label></div>
 <div style={{overflowX:'auto',margin:'20px 0',maxHeight:480}}><table style={{width:'100%',borderCollapse:'collapse',textAlign:'left'}}><thead><tr><th>Select</th><th>Customer</th><th>Number</th><th>Saved permission</th><th>Services / issue</th></tr></thead><tbody>{visible.map(r=><tr key={r.id} style={{borderBottom:'1px solid #dbe3e5'}}><td style={{padding:12}}><input type="checkbox" aria-label={`Select ${r.name}`} disabled={locked||!r.phone} checked={selected.includes(r.id)} onChange={e=>setSelected(old=>e.target.checked?[...old,r.id]:old.filter(id=>id!==r.id))}/></td><td>{r.name}</td><td>{r.phone||'Needs review'}</td><td title={!r.decision||r.decision.status==='unknown'?'Not verified':''}>{label(r.decision)}</td><td>{r.issue||((r.decision?.status==='accepted'&&r.decision.scope!=='all')?(r.decision.services||['Christmas lighting']).join(', '):'')}</td></tr>)}</tbody></table></div>
 <strong>{chosen.length} selected</strong><label style={{display:'block',marginTop:16}}>Apply to selected customers<select value={mode} disabled={locked} onChange={e=>setMode(e.target.value)}><option value="none">Choose what to save</option><option value="all">Accepted all OCF texts</option><option value="services">Accepted texts only for selected services</option><option value="declined">Do not send</option><option value="unknown">Clear to blank / not verified</option></select></label>{mode==='services'&&<fieldset><legend>Services these customers accepted</legend>{services.map(service=><label className="xmas-check" key={service}><input type="checkbox" checked={chosenServices.includes(service)} disabled={locked} onChange={e=>setChosenServices(old=>e.target.checked?[...old,service]:old.filter(s=>s!==service))}/>{service}</label>)}</fieldset>}<details><summary>Optional note for this group</summary><textarea aria-label="Permission note for selected customers" maxLength={700} value={note} disabled={locked} onChange={e=>setNote(e.target.value)}/></details><p className="staff-small">Saving records your firsthand report for each selected customer. It does not invent an original agreement date or send a text.</p><div className="xmas-actions"><button className="staff-primary" disabled={locked||!chosen.length||mode==='none'||(mode==='services'&&!chosenServices.length)} onClick={save}>Save selected ({chosen.length})</button><button className="staff-secondary" disabled={locked} onClick={onContinue}>Continue to campaign</button></div></section>;
}
