'use client';
import { useState } from 'react';
import CustomerPermission from './CustomerPermission';
import { campaignName } from '@/lib/staff/message-review';
type Customer = { id: string; name: string; isLead: boolean; isArchived: boolean };
type Review = {clientId:string;name:string;phone:string;phoneId:string;propertyId?:string;first:string;trackerRow:number;fingerprint:string;address?:string;messageCount:number;messages:{id:string;direction:string;text:string}[]};
type Result = {id:string;name:string;review?:Review;issue?:string};
type Props = {permissionRevision:number;request:(body?:Record<string,unknown>)=>Promise<any>;recipients:{clientIds:string[];phone:string;status:string;permissionHold?:boolean}[];disabled:boolean;onRefresh:()=>Promise<void>;onReview:()=>Promise<void>;onDetails:(customer?:Customer)=>void};
export default function QuickAudience({permissionRevision,request,recipients,disabled,onRefresh,onReview,onDetails}:Props){
 const [customers,setCustomers]=useState<Customer[]>([]),[selected,setSelected]=useState<string[]>([]),[after,setAfter]=useState<string|null>(null),[more,setMore]=useState(true),[busy,setBusy]=useState(false),[query,setQuery]=useState(''),[results,setResults]=useState<Result[]>([]),[notice,setNotice]=useState(''),[error,setError]=useState(''),[permissionById,setPermissionById]=useState<Record<string,string>>({});
 const queuedIds=new Set(recipients.filter(r=>!(r.status==='held'&&r.permissionHold)).flatMap(r=>r.clientIds));
 const available=customers.filter(c=>!queuedIds.has(c.id));
 const chosen=available.filter(c=>selected.includes(c.id));
 const ready=results.filter((r):r is Result & {review:Review}=>!!r.review&&selected.includes(r.id)&&!queuedIds.has(r.id));
 const queued=recipients.filter(r=>r.status==='queued').length;
 function changeSelection(ids:string[]){setSelected(ids);}
 async function load(){setBusy(true);setError('');try{const page=await request({operation:'clients',after});const added:Customer[]=page.records.filter((r:Customer)=>!r.isArchived&&!r.isLead&&!customers.some(c=>c.id===r.id));setCustomers(old=>[...old,...added]);setSelected(old=>[...new Set([...old,...added.filter(c=>!queuedIds.has(c.id)).map(c=>c.id)])]);setAfter(page.pageInfo.endCursor);setMore(page.pageInfo.hasNextPage);setNotice('Customers selected automatically. Uncheck anyone you want to leave out.');}catch(e){setError(e instanceof Error?e.message:'Could not load customers.');}finally{setBusy(false);}}
 async function check(){setBusy(true);setError('');setResults([]);const checked:Result[]=[];const phones=new Set<string>();try{for(const c of chosen.slice(0,10)){setNotice(`Checking ${checked.length+1} of ${Math.min(chosen.length,10)}: ${campaignName(c.name)}`);try{const review:Review=await request({operation:'quick_review',id:c.id});if(phones.has(review.phone)){checked.push({id:c.id,name:campaignName(c.name),issue:'Same household as another selected customer. Only one introduction will be queued.'});}else{phones.add(review.phone);checked.push({id:c.id,name:review.name,review});}}catch(e){checked.push({id:c.id,name:campaignName(c.name),issue:e instanceof Error?e.message:'Needs review.'});}setResults([...checked]);}setNotice('Checks complete. Only the ready customers below can be added. Nothing has been sent.');}finally{setBusy(false);}}
 async function reviewMessages(){if(!ready.length||ready.some(r=>(permissionById[r.id]||'').trim().length<15))return;setBusy(true);setError('');let added=0;try{for(const row of ready){const r=row.review;await request({operation:'approve',...r,permission:permissionById[row.id].trim(),smsConfirmed:true,threadReviewed:true});added++;setSelected(old=>old.filter(id=>id!==r.clientId));}await onRefresh();setResults([]);await onReview();}catch(e){setError((e instanceof Error?e.message:'Could not finish review.')+` ${added} customer(s) added; no texts sent. Refresh before retrying.`);try{await onRefresh();}catch{}}finally{setBusy(false);}}
 const locked=busy||disabled;
 return <div className="xmas-two-col"><section className="staff-panel"><span className="staff-eyebrow">1 / CHOOSE CUSTOMERS</span><h2>Who should get your Christmas offer?</h2><p>Select everyone you want, then uncheck anyone to leave out. We will check and prepare up to 10 at a time.</p>{error&&<div className="staff-alert" role="alert">{error}</div>}{notice&&<p role="status" aria-live="polite">{notice}</p>}
 {!customers.length?<button className="staff-primary" disabled={locked} onClick={load}>{busy?'Loading customers…':'Load up to 200 customers'}</button>:<><div className="xmas-actions"><button className="staff-secondary" disabled={locked} onClick={()=>changeSelection(available.map(c=>c.id))}>Select all {available.length} loaded customers</button><button className="staff-secondary" disabled={locked||!selected.length} onClick={()=>changeSelection([])}>Clear selection</button></div><p><strong>{chosen.length} selected</strong> · {customers.length} loaded{more?' · More customers available below':''}</p><label htmlFor="quick-search">Find a customer</label><input id="quick-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search loaded names"/><div className="xmas-customer-list">{available.filter(c=>campaignName(c.name).toLowerCase().includes(query.toLowerCase())).map(c=><label className="xmas-check" key={c.id}><input type="checkbox" checked={selected.includes(c.id)} disabled={locked} onChange={e=>changeSelection(e.target.checked?[...selected,c.id]:selected.filter(id=>id!==c.id))}/><span>{campaignName(c.name)||'Name needs review'}</span></label>)}</div>{more&&<button className="staff-secondary" disabled={locked} onClick={load}>Load next 200 customers</button>}<div className="xmas-actions"><button className="staff-primary" disabled={locked||!chosen.length} onClick={check}>{busy?'Checking…':`Check next ${Math.min(chosen.length,10)} selected customers`}</button></div></>}
 <p className="staff-small">Only existing active customers are loaded. Selecting customers does not send texts or establish permission. Already queued or processed customers are excluded.</p></section>
 <section className="staff-panel"><span className="staff-eyebrow">2 / REVIEW & CONTINUE</span><h2>{ready.length?`${ready.length} ready for your review`:'We fill in the details for you.'}</h2>{!results.length&&<p>The website chooses a unique saved number, links the outreach record, checks current conversations, and removes duplicate households. You do not need to type spreadsheet row numbers.</p>}{results.map(row=><article key={row.id} style={{borderBottom:'1px solid #e2e8f0',padding:'14px 0'}}><strong>{row.name}</strong>{row.review?<><p>{row.review.phone}</p><p className="xmas-good">Details filled in · Greeting: {row.review.first}</p><details><summary>Conversation review ({row.review.messageCount} messages)</summary>{row.review.messages.length?row.review.messages.map(m=><p key={m.id}><strong>{m.direction==='incoming'?'Customer':'OCF'}:</strong> {m.text}</p>):<p>No messages found. Your saved customer permission is used below.</p>}</details><CustomerPermission key={`${row.id}-${permissionRevision}`} identity={row.review} request={request} disabled={locked} onSaved={value=>{setPermissionById(old=>old[row.id]===value?old:{...old,[row.id]:value});}}/></>:<><p className="staff-small">{row.issue}</p><button className="staff-secondary" disabled={locked} onClick={()=>onDetails(customers.find(c=>c.id===row.id))}>Resolve {row.name}</button><button className="staff-secondary" disabled={locked} onClick={()=>changeSelection(selected.filter(id=>id!==row.id))}>Skip for now</button></>}</article>)}
 {ready.length>0&&<><p>Uses the customer permissions you already saved. Adding to the queue does not send a text.</p><button className="staff-primary" disabled={locked||ready.some(r=>(permissionById[r.id]||'').trim().length<15)} onClick={reviewMessages}>Queue {ready.length} customers →</button></>}
 {queued>0&&<p><button className="staff-secondary" disabled={locked} onClick={onReview}>Review {queued} already queued customers →</button></p>}
 {results.some(r=>r.issue)&&<details><summary>Customers needing attention</summary><p>Uncheck them to continue with the ready customers. Conflicting records, opt-outs and missing information are never silently cleared.</p><button className="staff-secondary" disabled={locked} onClick={()=>onDetails()}>Open individual review</button></details>}
 <p><button className="staff-secondary" disabled={locked} onClick={()=>onDetails()}>Edit customer acceptance</button></p><p className="staff-small">You will see every final text before pressing Send batch now. Sending limits may make a batch smaller than 10.</p></section></div>;
}
