export type Review = { name: string; service: string; date: string; quote: string; source: 'Thumbtack' };

export const reviews: Review[] = [
  { name: 'Massimo M.', service: 'Gutter Cleaning and Maintenance', date: 'Mar 2, 2026', quote: 'Excellent job cleaning my house gutters. Will use them again.', source: 'Thumbtack' },
  { name: 'Sabrina R.', service: 'Gutter Cleaning and Maintenance', date: 'Nov 5, 2025', quote: 'Eric and his team came out and did a great job. They were early, cleaned up well after the job, and made quick work of the years of build up. Strongly considering them to come back in March to do another round after the fall leaves all come down.', source: 'Thumbtack' },
  { name: 'Lea M.', service: 'Gutter Cleaning and Maintenance', date: 'Sep 21, 2025', quote: 'Customer focused. Worked per our requested specifications to avoid damage to landscape and pool.', source: 'Thumbtack' },
  { name: 'Zack A.', service: 'Gutter Cleaning and Maintenance', date: 'Aug 8, 2025', quote: 'Eric performed exceptionally well and his communication was flawless. He was incredibly friendly, completed the job efficiently, and left the house spotless, just as he found it. He also took out all the trash from the gutters. I highly recommend him to anyone.', source: 'Thumbtack' },
  { name: 'Bill C.', service: 'Gutter Cleaning and Maintenance', date: 'Jul 4, 2025', quote: 'Eric & his assistant did an excellent job cleaning and flushing our gutters. Verified by the storm that came about an hour after they left. They responded quickly and cleaned up everything. No doubt we’ll be using them again.', source: 'Thumbtack' },
  { name: 'Ted H.', service: 'Gutter Cleaning and Maintenance', date: 'Jul 12, 2025', quote: 'Eric did a great and thorough job cleaning and unclogging my gutters. I would use him again, and recommend him to anyone.', source: 'Thumbtack' },
  { name: 'Jim N.', service: 'Gutter Cleaning and Maintenance', date: 'Jul 25, 2025', quote: 'Work was done quickly and efficiently. Enjoyed the opportunity to work with a Veteran', source: 'Thumbtack' },
  { name: 'Marchette W.', service: 'Window Cleaning', date: 'May 7, 2025', quote: 'Eric was thorough giving special attention to paint speckles left from another contractor. He brought to my attention the different styles of glass in my home that scratch easily. The green algae that had built up was removed. I will use Eric again for cleaning my exterior windows.', source: 'Thumbtack' },
  { name: 'Meredith M.', service: 'Gutter Cleaning and Maintenance', date: 'Dec 20, 2024', quote: 'Eric and his crew did a wonderful job cleaning our gutters and getting rid of the mold on the roof! The cleaning was meticulous and super thorough!! We will be hiring them for all of our gutter cleanings going forward. Highly recommend!', source: 'Thumbtack' },
  { name: 'Mary C.', service: 'Gutter Cleaning and Maintenance', date: 'Jul 2, 2024', quote: 'Eric did a great job. He was efficient, polite, professional, and hard working. I highly recommend him and will definitely hire him again.', source: 'Thumbtack' }
];
